// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-service/user-service.proto

package user_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	base "grpc-gateway/proto/base"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserId struct {
	UserId               int64                   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BaseParams           *base.BaseRequestParams `protobuf:"bytes,2,opt,name=baseParams,proto3" json:"baseParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e882b7622885a4db, []int{0}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserId) GetBaseParams() *base.BaseRequestParams {
	if m != nil {
		return m.BaseParams
	}
	return nil
}

type UserInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e882b7622885a4db, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func init() {
	proto.RegisterType((*UserId)(nil), "grpc.gateway.proto.user.service.UserId")
	proto.RegisterType((*UserInfo)(nil), "grpc.gateway.proto.user.service.UserInfo")
}

func init() { proto.RegisterFile("user-service/user-service.proto", fileDescriptor_e882b7622885a4db) }

var fileDescriptor_e882b7622885a4db = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x47, 0xe6, 0xe8, 0x15, 0x14, 0xe5, 0x97,
	0xe4, 0x0b, 0xc9, 0xa7, 0x17, 0x15, 0x24, 0xeb, 0xa5, 0x27, 0x96, 0xa4, 0x96, 0x27, 0x56, 0x42,
	0xc4, 0xf4, 0x40, 0xca, 0xf4, 0xa0, 0xca, 0xa4, 0x64, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5,
	0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21,
	0x4a, 0xa5, 0x94, 0x40, 0xda, 0x75, 0xa1, 0xda, 0xf5, 0xc1, 0x62, 0xfa, 0x49, 0x89, 0xc5, 0xa9,
	0x60, 0x02, 0xa2, 0x46, 0x29, 0x87, 0x8b, 0x2d, 0xb4, 0x38, 0xb5, 0xc8, 0x33, 0x45, 0x48, 0x8c,
	0x8b, 0xad, 0x14, 0xcc, 0x92, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf2, 0x84, 0xbc, 0xb8,
	0xb8, 0x40, 0xea, 0x03, 0x12, 0x8b, 0x12, 0x73, 0x8b, 0x25, 0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d,
	0xb4, 0xf4, 0xb0, 0xb8, 0x0c, 0x6c, 0xaa, 0x53, 0x62, 0x71, 0x6a, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x09, 0x44, 0x47, 0x10, 0x92, 0x6e, 0x25, 0x3f, 0x2e, 0x0e, 0xb0, 0x6d, 0x79, 0x69, 0xf9,
	0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x30, 0xbb, 0x98, 0x32, 0x91, 0xed, 0x67, 0x42, 0xb1, 0x5f, 0x8a,
	0x8b, 0x23, 0x2f, 0x33, 0x39, 0xdb, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33,
	0x08, 0xce, 0x37, 0x3a, 0xc1, 0xc8, 0xc5, 0x0d, 0x32, 0x30, 0x18, 0x12, 0x1e, 0x42, 0x3b, 0x18,
	0xb9, 0xb8, 0xdd, 0x53, 0x4b, 0xe0, 0x76, 0xa8, 0xeb, 0x11, 0x08, 0x41, 0x3d, 0x88, 0xe7, 0xa5,
	0x34, 0x89, 0x53, 0x98, 0x97, 0x96, 0xaf, 0x14, 0xda, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x7f, 0x21,
	0x69, 0x7d, 0x03, 0x43, 0x70, 0xa4, 0xe9, 0xa7, 0xa7, 0x96, 0x80, 0x64, 0xf4, 0xab, 0x21, 0x2e,
	0xb6, 0xd5, 0xaa, 0x8d, 0x32, 0x10, 0xd2, 0xc3, 0x25, 0x5d, 0xab, 0x5f, 0x8d, 0x08, 0x11, 0xbd,
	0xb2, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0xbc, 0x5a, 0x27, 0xbe, 0x28, 0x1e, 0xe4, 0x14, 0x90, 0xc4,
	0x06, 0x76, 0x83, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xcb, 0x28, 0x1e, 0x25, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserInfo(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserInfo, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/grpc.gateway.proto.user.service.UserService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUserInfo(context.Context, *UserId) (*UserInfo, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUserInfo(ctx context.Context, req *UserId) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.proto.user.service.UserService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.proto.user.service.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service/user-service.proto",
}
