// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseRequestParams struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Host                 string   `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	RequestId            string   `protobuf:"bytes,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequestParams) Reset()         { *m = BaseRequestParams{} }
func (m *BaseRequestParams) String() string { return proto.CompactTextString(m) }
func (*BaseRequestParams) ProtoMessage()    {}
func (*BaseRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66ec2e140567106, []int{0}
}

func (m *BaseRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequestParams.Unmarshal(m, b)
}
func (m *BaseRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequestParams.Marshal(b, m, deterministic)
}
func (m *BaseRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequestParams.Merge(m, src)
}
func (m *BaseRequestParams) XXX_Size() int {
	return xxx_messageInfo_BaseRequestParams.Size(m)
}
func (m *BaseRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequestParams proto.InternalMessageInfo

func (m *BaseRequestParams) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BaseRequestParams) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *BaseRequestParams) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseRequestParams) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *BaseRequestParams) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BaseRequestParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseRequestParams)(nil), "grpc.gateway.proto.base.BaseRequestParams")
}

func init() { proto.RegisterFile("base/base.proto", fileDescriptor_d66ec2e140567106) }

var fileDescriptor_d66ec2e140567106 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4a, 0x2c, 0x4e,
	0xd5, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xe2, 0xe9, 0x45, 0x05, 0xc9, 0x7a,
	0xe9, 0x89, 0x25, 0xa9, 0xe5, 0x89, 0x95, 0x10, 0x31, 0x3d, 0x90, 0xb4, 0xd2, 0x6c, 0x46, 0x2e,
	0x41, 0xa7, 0xc4, 0xe2, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x92, 0x80, 0xc4, 0xa2, 0xc4,
	0xdc, 0x62, 0x21, 0x09, 0x2e, 0xf6, 0xb2, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x88, 0x8b, 0x25, 0x27, 0x31, 0x2f, 0x5d, 0x82, 0x09,
	0x2c, 0x0c, 0x66, 0x0b, 0xf1, 0x71, 0x31, 0x65, 0x16, 0x48, 0x30, 0x83, 0x45, 0x98, 0x32, 0x0b,
	0x84, 0xc4, 0xb8, 0xd8, 0x52, 0x52, 0xcb, 0x32, 0x93, 0x53, 0x25, 0x58, 0xc0, 0x62, 0x50, 0x1e,
	0x48, 0x6f, 0x46, 0x7e, 0x71, 0x89, 0x04, 0x2b, 0x44, 0x2f, 0x88, 0x2d, 0x24, 0xc3, 0xc5, 0x59,
	0x04, 0xb1, 0xda, 0x33, 0x45, 0x82, 0x0d, 0x2c, 0x81, 0x10, 0x70, 0x62, 0x8b, 0x62, 0x01, 0xb9,
	0x32, 0x89, 0x0d, 0xec, 0x62, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x98, 0x27, 0xa5,
	0xd8, 0x00, 0x00, 0x00,
}
