// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommonParam struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Host                 string   `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	RequestId            string   `protobuf:"bytes,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonParam) Reset()         { *m = CommonParam{} }
func (m *CommonParam) String() string { return proto.CompactTextString(m) }
func (*CommonParam) ProtoMessage()    {}
func (*CommonParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66ec2e140567106, []int{0}
}

func (m *CommonParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonParam.Unmarshal(m, b)
}
func (m *CommonParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonParam.Marshal(b, m, deterministic)
}
func (m *CommonParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonParam.Merge(m, src)
}
func (m *CommonParam) XXX_Size() int {
	return xxx_messageInfo_CommonParam.Size(m)
}
func (m *CommonParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonParam.DiscardUnknown(m)
}

var xxx_messageInfo_CommonParam proto.InternalMessageInfo

func (m *CommonParam) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CommonParam) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *CommonParam) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CommonParam) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *CommonParam) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CommonParam) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type Session struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	LoginAccount         string   `protobuf:"bytes,3,opt,name=loginAccount,proto3" json:"loginAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66ec2e140567106, []int{1}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Session) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Session) GetLoginAccount() string {
	if m != nil {
		return m.LoginAccount
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonParam)(nil), "base.CommonParam")
	proto.RegisterType((*Session)(nil), "base.Session")
}

func init() { proto.RegisterFile("base/base.proto", fileDescriptor_d66ec2e140567106) }

var fileDescriptor_d66ec2e140567106 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xd9, 0xbd, 0x35, 0xe7, 0x8d, 0xa2, 0x30, 0xc5, 0x11, 0xc4, 0x42, 0xb6, 0xb2, 0xd2,
	0xc2, 0x27, 0x50, 0xab, 0x6b, 0x44, 0xce, 0xce, 0x2e, 0x97, 0x1d, 0xce, 0xe0, 0x25, 0xb3, 0x26,
	0xd9, 0x7d, 0x13, 0xdf, 0x57, 0x32, 0x46, 0xc5, 0x26, 0xfc, 0xdf, 0x17, 0x86, 0xf9, 0x19, 0x38,
	0xdf, 0x99, 0x44, 0xb7, 0xe5, 0xb9, 0x19, 0x23, 0x67, 0xc6, 0xae, 0xe4, 0xfe, 0xb3, 0x81, 0x93,
	0x47, 0xf6, 0x9e, 0xc3, 0xb3, 0x89, 0xc6, 0xa3, 0x86, 0xe5, 0x4c, 0x31, 0x39, 0x0e, 0xba, 0xb9,
	0x6a, 0xae, 0x57, 0xdb, 0x1f, 0x44, 0x84, 0xee, 0x60, 0xc2, 0x5e, 0xb7, 0xa2, 0x25, 0xe3, 0x19,
	0xb4, 0x6e, 0xd4, 0x0b, 0x31, 0xad, 0x1b, 0x71, 0x0d, 0x6a, 0xa0, 0xd9, 0x59, 0xd2, 0x9d, 0xb8,
	0x4a, 0x65, 0xf6, 0x8d, 0x53, 0xd6, 0x47, 0xdf, 0xb3, 0x25, 0xe3, 0x25, 0xac, 0x22, 0x7d, 0x4c,
	0x94, 0xf2, 0x66, 0xd0, 0x4a, 0x3e, 0xfe, 0x44, 0x6f, 0x60, 0xf9, 0x42, 0x49, 0x16, 0xaf, 0x41,
	0x4d, 0x89, 0xe2, 0x66, 0x90, 0x46, 0x8b, 0x6d, 0x25, 0xbc, 0x80, 0xe3, 0xe0, 0xec, 0xfb, 0x93,
	0xf1, 0x54, 0x4b, 0xfd, 0x32, 0xf6, 0x70, 0x7a, 0xe0, 0xbd, 0x0b, 0xf7, 0xd6, 0xf2, 0x14, 0x72,
	0xad, 0xf8, 0xcf, 0x3d, 0xa8, 0x57, 0x39, 0xc1, 0x4e, 0xc9, 0x3d, 0xee, 0xbe, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x22, 0xb6, 0xde, 0x22, 0x01, 0x00, 0x00,
}
